### ISSUE TITLE
Drag placment will be cancelled if dragging ends in ui elements

### ISSUE THREAD

**Issue by Sennel** [Bouncyrock/TaleSpire-Alpha-Public-Issue-Tracker#20]
While trying to drag and drop tiles, ending the drag and drop on a button or the bottom shortcut bar causes the action to not complete and the drag box to remain on screen.

**Comment by MarcLobster** [comment]
Confirming this still happened as of this time in Alpha testing

https://clips.twitch.tv/DreamySecretiveWalletBuddhaBar

**Comment by cbaggers** [comment]
heya. I just pushed a fix for this internally. If it holds up then it'll be in the next update

**Comment by cbaggers** [comment]
Vid from @RPGKenL https://streamable.com/swpnf

**Comment by cbaggers** [comment]
This should be fixed in the latest update. I'm gonna close this for now, feel free to comment here if I'm wrong and i'll reopen it :)

**Comment by ryvaeus** [comment]
I see it still happening. This clip was from the Dicecast stream earlier today. https://clips.twitch.tv/FitCourageousFungusSpicyBoy

**Comment by cbaggers** [comment]
@ryvaeus Ah, that's the same kind of bug but for drag selection rather than 'drag to build'. The originally reported issue is fixed but I didnt fix this very similar one. On it

**Comment by cbaggers** [comment]
Looks better internally now https://streamable.com/rz3tk

**Comment by ryvaeus** [comment]
Just noting that hopefully your internal fixes to this issue also fixed what I suspect is a related problem in issue #22
